### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by The-Scout** [Athlon007/MOP#140] opened 2022-09-16 17:25 UTC
**Describe the bug**
Booze, and other items despawning, when purchases.

**To Reproduce**
1. Go Teimos
2. Click on Beer
3. Purchase
4. Poof
5. See error

**Expected behavior**
Items spawning, and not dissapearing

**Mod Report:**
[MOP Bug Report - 2022-09-16_12-22.zip](https://github.com/Athlon007/MOP/files/9586014/MOP.Bug.Report.-.2022-09-16_12-22.zip)

**Additional context**
Mods Folder:  https://drive.google.com/file/d/1GuFGPNRtExAGR0NRXneEah9pDeOKE3dS/view?usp=drivesdk

**Comment by The-Scout** [comment] 2022-09-16 17:52
Removed all mods I think, and still happening.

**Comment by Athlon007** [comment] 2022-09-16 22:31
I doubt it's actually due to MOP, because It happens even without MOP running.

**Comment by The-Scout** [comment] 2022-09-17 05:51
Did I run into an obscure vanilla bug, or did one of the mods fuck the save file?

**Comment by Athlon007** [comment] 2022-09-17 09:19
> Did I run into an obscure vanilla bug, or did one of the mods fuck the save file?

I have no clue. In theory, save file state should not be able affect ability of certain items to spawn. I have contacted ToplessGun about it, and I'm waiting for the response.

**Comment by Athlon007** [comment] 2022-09-17 09:59
Ok, I found where the issue is. For some reason, the ID of last purchased beer case has not been increased in the items.txt. It can be fixed by setting the "beercase" value to the ID of the last beer case.

I'll try to implement a fix targeting that :)

**Comment by The-Scout** [comment] 2022-09-17 19:03
Does that also explain other items despawning?

**Comment by The-Scout** [comment] 2022-09-17 19:06
How do I download the beta?

**Comment by The-Scout** [comment] 2022-09-17 19:13
That fixed it!!

**Comment by Athlon007** [comment] 2022-09-19 11:09
Fixed in 3.9.

**Closed by Athlon007** 2022-09-19 11:09 UTC
Labels: needs more info, vanilla bug
