### ISSUE TITLE
My teimon purchases are not showing up after I purchase something...

### ISSUE THREAD

**Issue by V-SpecR34** [Athlon007/MOP#43] opened 2022-01-03 20:36 UTC
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Game Version:** [e.g. 15.11.2019/Experimental]

**Mod Report:**
 [Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by ChangeDev** [comment] 2022-01-03 21:17
Can confirm, also reported it before. #42

**Comment by Athlon007** [comment] 2022-01-03 21:33
Duplicate of #42. Closing.

**Closed by Athlon007** 2022-01-03 21:33 UTC
