### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Cloudiergorgon7** [Athlon007/MOP#176] opened 2022-12-06 17:30 UTC
All I did to reproduce is loaded into the save then the modloader console appeared and spit out saying there was a bug and to report it
**Additional context**
[Add any other context about the problem here.]
[MOP Bug Report - 2022-12-06_12-29.zip](https://github.com/Athlon007/MOP/files/10168856/MOP.Bug.Report.-.2022-12-06_12-29.zip)

**Comment by Athlon007** [comment] 2022-12-09 19:15
Duplicate of #173

**Closed by Athlon007** 2022-12-09 19:15 UTC
