### ISSUE TITLE
White blocks appearing on the Satsuma's body

### ISSUE THREAD

**Issue by Justincatalot20** [Athlon007/MOP#60] opened 2022-04-16 03:09 UTC
White boxes around satsuma. When I delete MOP fully it goes away. See problem below
![Screenshot (5)](https://user-images.githubusercontent.com/103801934/163659172-9600a234-6275-4897-b110-c2a7fe48b5c8.png)

Expected Satsuma to be perfectly fine. 

Full MOP Report below.
[MOP_Report_0.txt](https://github.com/Athlon007/MOP/files/8499157/MOP_Report_0.txt)
[MOP Bug Report - 2022-04-15_23-03.zip](https://github.com/Athlon007/MOP/files/8499158/MOP.Bug.Report.-.2022-04-15_23-03.zip)

**Comment by Athlon007** [comment] 2022-04-16 08:50
Hi there,
Thanks for reporting the bug. This kind of issues are caused by other mods using [Primitives](https://docs.unity3d.com/510/Documentation/Manual/PrimitiveObjects.html), instead of creating new object without renderer. One solution is to try and disable one mod at the time and see if the issue persists.

**Comment by Athlon007** [comment] 2022-04-16 21:36
Fixed in 3.6.2.

**Closed by Athlon007** 2022-04-16 21:36 UTC
Labels: bug
