### ISSUE TITLE
satsuma teleports back to the garage (last saved position) and glitched

### ISSUE THREAD

**Issue by tonimark** [Athlon007/MOP#20] opened 2020-04-10 07:57 UTC
**Describe the bug**
[A clear and concise description of what the bug is.]
after leaving the satsuma in any place, it will teleport back to garage completely glitched out 
**To Reproduce**
[Steps to reproduce the behavior:
1. leave the satsuma in any place 
2. return 
3. See error satsuma is gone
4. go back to the garage (last saved position), you will see satsuma broken

**Expected behavior**
[A clear and concise description of what you expected to happen.]
satsuma would be located in the last place I parked it
**Screenshots**
[If applicable, add screenshots to help explain your problem.]
glitch is random, but for sure satsuma returns to garage 
**Game Version:** Experimental: last update 8 April of 2020

**Mod Report:**
 [Go into mod settings and click "Generate mod report", and paste the content here]
[MOP_REPORT.txt](https://github.com/Athlon007/MOP/files/4460499/MOP_REPORT.txt)

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment] 2020-04-12 09:20
Can't reproduce it

**Comment by Athlon007** [comment] 2020-04-12 23:21
MOP 2.6.1 should fix that. Please try it and report back.

**Comment by Athlon007** [comment] 2020-04-14 11:33
I'm considering this as fixed. Closing.

**Closed by Athlon007** 2020-04-14 11:33 UTC
Labels: bug, help wanted
