### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by stagea260rs** [Athlon007/MOP#133] opened 2022-08-28 04:33 UTC
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Steps to reproduce the behavior:
[MOP Bug Report - 2022-08-28_13-27.zip](https://github.com/Athlon007/MOP/files/9439087/MOP.Bug.Report.-.2022-08-28_13-27.zip)

4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[MOP Bug Report - 2022-08-28_13-27.zip](https://github.com/Athlon007/MOP/files/9439088/MOP.Bug.Report.-.2022-08-28_13-27.zip)

[Add any other context about the problem here.]

**Comment by Athlon007** [comment] 2022-08-28 10:17
Duplicate of #134

**Closed by Athlon007** 2022-08-28 10:17 UTC
