### ISSUE TITLE
Bug Report MOP v3.7.2

### ISSUE THREAD

**Issue by JaxBoyo** [Athlon007/MOP#107] opened 2022-07-14 21:44 UTC
**Bugs:**
- when bringing fish to grandma, the fish are under her table upon saving & reloading game and can't be picked up
- grandma called on sunday to drive her to church but when i came to her house she was not there despite me coming immediately
- grandma disappeared: she stopped calling and isn't outside even on nice days
- gas tank, muffler, exhaust & battery sometimes fall off the car when starting the game
- CD is not spawning anywhere despite naming tracks "track1.ogg..." and importing music in the main menu (tracks are in .ogg format and in CD1 file), CD is also not at the landfill
- buying food and saving & reloading the game makes purchased food spawn at landfill
- i randomly fell through the map when walking on dirt road at landfill (not sure if it's a MOP bug or game bug)

**To Reproduce**
X

**Expected behavior**
X

**Mod Report:**
[MOP Bug Report - 2022-07-14_22-58.zip](https://github.com/Athlon007/MOP/files/9115478/MOP.Bug.Report.-.2022-07-14_22-58.zip)

**Additional context**
Thank you for making this mod and for taking your time to fix bugs and updating it :)

**Comment by Athlon007** [comment] 2022-07-14 22:04
Grandma might've been ran over by the green car, as her status is dead in your save file.

**Comment by Athlon007** [comment] 2022-07-14 22:46
Fish bug I can confirm, will be fixed in the next update.

CD does spawn fine for me on your save file - right on the kitchen table (tested on MOP 3.8):
![Screenshot 2022-07-15 at 00 19 31](https://user-images.githubusercontent.com/24318504/179098073-40be2ce8-7fa0-4425-b20d-15575315d5bd.png)
 
I've attempted reproducing the food items purchased spawning at landfill - I could not reproduce it (I've tried placing sausages and the shopping bag set away from me when saving, and both of two close to me while saving).

As for the falling through the map - I honestly have no idea where and how this could happen. MOP does not disable colliders around the landfill, nor I can't find any hole in the level's geometry (perhaps if you could narrow down the exact spot where did you fall through the map?).

As for parts randomly detaching, MSC's physics engine is basically broken at extremely low frame rate. I can't do much more to help in your case, as Celeron N2840 is plain slow, and I don't think it can even keep up with Unity's physics simulation, which can lead to issues you've described.

**Closed by Athlon007** 2022-07-14 22:46 UTC
