### ISSUE TITLE
Weird white blocks on car parts

### ISSUE THREAD

**Issue by LordJames420** [Athlon007/MOP#59] opened 2022-04-15 22:02 UTC
[MOP Bug Report - 2022-04-15_15-58.zip](https://github.com/Athlon007/MOP/files/8498450/MOP.Bug.Report.-.2022-04-15_15-58.zip)

**Comment by Athlon007** [comment] 2022-04-16 08:55
Duplicate of #60

**Closed by Athlon007** 2022-04-16 08:55 UTC
