### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by brendojohn** [Athlon007/MOP#178] opened 2022-12-07 01:56 UTC
Started to appear since the last MSC update.

[MOP Bug Report - 2022-12-06_21-41.zip](https://github.com/Athlon007/MOP/files/10172091/MOP.Bug.Report.-.2022-12-06_21-41.zip)

**Comment by Athlon007** [comment] 2022-12-09 19:15
Duplicate of #173

**Closed by Athlon007** 2022-12-09 19:15 UTC
