### ISSUE TITLE
Verify save file bug

### ISSUE THREAD

**Issue by MrOirz** [Athlon007/MOP#128] opened 2022-08-20 06:01 UTC
**Describe the bug**
[A clear and concise description of what the bug is.]
[MOP Bug Report - 2022-08-20_12-57.zip](https://github.com/Athlon007/MOP/files/9386336/MOP.Bug.Report.-.2022-08-20_12-57.zip)

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Mod Report:**
[Go into mod settings and click "I FOUND A BUG", and paste the content here]

**Additional context**
[Add any other context about the problem here.]

**Comment by Athlon007** [comment] 2022-08-20 09:52
Sorry, but the pirated game copies are not supported.

**Comment by putangina-mo** [comment] 2022-08-21 03:13
I believe the bug came from steam itself. Sometimes steam just won't trigger of you owning the game when opening it, even the modloader does not detect that I am using the legitimate copy of the game. A simple steam restart would fix it, but however I am not sure if this is the case. Because It happened to me once and it only took me a restart

**Comment by Athlon007** [comment] 2022-08-21 10:55
> I believe the bug came from steam itself. Sometimes steam just won't trigger of you owning the game when opening it, even the modloader does not detect that I am using the legitimate copy of the game. A simple steam restart would fix it, but however I am not sure if this is the case. Because It happened to me once and it only took me a restart

MOP doesn't check if you have a legal copy of MSC. One can tell if a legal copy of MSC is being used or not by checking where the game is stored - it's absolutely normal to have a path saying "steamapps/common/My Summer Car", but it's very suspicious if a path is "Downloads/Compressed/My.Summer.Car.v04.04.2022", which correlates the folder structure of Skidrow's repack. My policy on pirated game copies is as follows: if MOP works fine on your pirated copy, I don't care. If the MOP doesn't work - you're out of luck. The main reason why I have such policy, is because some copies might be outdated, and it's hard for me to maintain MOP for every single version of MSC.

As of this bug, it seems to be caused by creating a new save file, then quitting without saving, which can occur on any version of MSC.

**Comment by Athlon007** [comment] 2022-08-23 14:43
Fixed in 3.8.3

**Closed by Athlon007** 2022-08-23 14:43 UTC
Labels: bug, confirmed
